### ISSUE TITLE
Double usage of variable "R" in models

### ISSUE THREAD

**Issue by dietmarw** [mtiller/ModelicaBook#310]
This is taken from #163 in order to get that meta ticket cleaned up:

In http://book.xogeny.com/components/components/chem_comps/

The variable R in Mixture appears to be a vector containing the concentration rates of the three species A, B and X. Later, in X+B->R+S, R is described as an intermediate species.'

There is also a TODO for the results that needs fixing.

**Comment by mtiller** [comment]
Slight update.  I don't see a TODO in there.  But I assume the duplicate usage is that `R` is used to represent the reaction rate on the connector but also the intermediate species in the reaction.  It would probably be best to just rename the intermediate species to `T`.  That will involve changing the Modelica code, probably the `specs.py` file and the text in `chem_comp.rst`.  But it seems reasonably contained.  I'll try and do all that in a single commit and then check the result in the preview site.

**Comment by mtiller** [comment]
Should be fixed in 0e8229ecc041f234d35e861a5130fc991af4913a.  I want to wait until the next build to really know for sure that I got everything that needs to change.  But I think so.

This really was very confusing, thanks for reporting this.  Looking back, it was pretty poor planning to using `R` in both of these ways and, TBH, I'm a little disappointed in myself for writing something so confusing.

**Comment by mtiller** [comment]
As far as I can tell, this issue is resolved.
